import type { Metadata } from "next"
import "../styles/globals.scss"
import "../styles/tailwind.css"
import Nav from "../components/Nav/Nav"
import Footer from "../components/Footer/Footer"
import { gothamFont } from "@/utils/gothamFont"
import BreadCrumb from "@/components/BreadCrumb"

export const metadata: Metadata = {
    title: "Hedooh",
    description: "Generated by create next app"
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={gothamFont.className}>
                <BreadCrumb />
                <Nav />
                {children}
                <Footer />
            </body>
        </html>
    )
}
